import { IProduct } from '@/types/types'

export const products: Array<IProduct> = [
  { name: 'Apple', calories: 95 },
  { name: 'Banana', calories: 105 },
  { name: 'Orange', calories: 62 },
  { name: 'Grapes', calories: 69 },
  { name: 'Strawberries', calories: 49 },
  { name: 'Blueberries', calories: 57 },
  { name: 'Raspberries', calories: 64 },
  { name: 'Watermelon', calories: 46 },
  { name: 'Pineapple', calories: 82 },
  { name: 'Mango', calories: 135 },
  { name: 'Peach', calories: 59 },
  { name: 'Plum', calories: 46 },
  { name: 'Pear', calories: 101 },
  { name: 'Grapefruit', calories: 52 },
  { name: 'Avocado', calories: 234 },
  { name: 'Tomato', calories: 22 },
  { name: 'Cucumber', calories: 16 },
  { name: 'Carrot', calories: 41 },
  { name: 'Broccoli', calories: 55 },
  { name: 'Spinach', calories: 23 },
  { name: 'Lettuce', calories: 5 },
  { name: 'Chicken Breast', calories: 165 },
  { name: 'Salmon', calories: 206 },
  { name: 'Tuna', calories: 179 },
  { name: 'Beef Steak', calories: 250 },
  { name: 'Pork Chop', calories: 221 },
  { name: 'Egg', calories: 78 },
  { name: 'Bread', calories: 79 },
  { name: 'Rice', calories: 130 },
  { name: 'Pasta', calories: 131 },
  { name: 'Potato', calories: 130 },
  { name: 'Sweet Potato', calories: 103 },
  { name: 'Oatmeal', calories: 150 },
  { name: 'Yogurt', calories: 150 },
  { name: 'Milk', calories: 103 },
  { name: 'Cheese', calories: 113 },
  { name: 'Peanut Butter', calories: 190 },
  { name: 'Almonds', calories: 164 },
  { name: 'Walnuts', calories: 185 },
  { name: 'Cashews', calories: 155 },
  { name: 'Dark Chocolate', calories: 170 },
  { name: 'Milk Chocolate', calories: 230 },
]
